services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    command: run dev
    environment:
    - NODE_ENV=development
    env_file: .env
    image: ${DOCKER_REG}${SERVICE_NAME}
    ports:
    - ${PORT}:${PORT}
    - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
    - ./:/code
    - /code/node_modules
version: "3.4"
