services:
  app:
    build: .
    command: run dev
    environment:
    - NODE_ENV=development
    env_file: .env
    image: ${DOCKER_REG}${SERVICE_NAME}
    network_mode: bridge
    ports:
    - ${PORT}:${PORT}
version: "3"
